# Generated by Django 4.0.3 on 2022-04-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imagefile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
