# Generated by Django 4.0.3 on 2022-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbook', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
