# Generated by Django 4.0.3 on 2022-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbook', '0003_image_author_image_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('imagefile', models.FileField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
